### ISSUE TITLE
Spreadsheet.destroy()

### ISSUE THREAD

**Issue by Nickesh** [MX-5ClubPoland/MMCLapTimer#15]
Trzeba dokończyć destroy'a spreadsheetów. Musi przerywać bieżące requesty AJAX-owe i czyścić zaalokowaną pamięć.

**Comment by zrwsk** [comment]
Dopisałem,  GC to zbiera więc jest chyba spoko.

BTW. Nie dodałeś obrazków które masz w layoucie.

**Comment by Nickesh** [comment]
Działa świetnie. Dzięki! :)
