### ISSUE TITLE
Po co lapsRace i lapsPractice?

### ISSUE THREAD

**Issue by Nickesh** [MX-5ClubPoland/MMCLapTimer#5]
W pomiarze wyników bierzemy pod uwagę po prostu wszystkie czasy, wpisane do spreadsheeta. Nie jest istotne, ile kółek jest zaplanowanych na trening, czy rallysprint. Myślę, że można wywalić te zmienne z configa.

**Comment by jaroslawfrydrych** [comment]
Co do praktyki to się zgadzam. Co do race laps to potrzebne są ze względu na to, że odliczane są najgorsze okrązenia, nie brane są wszystkie pod uwagę w kwestii wyniku sumarycznego rallysprintu.

**Comment by Nickesh** [comment]
Dokładnie, ale właśnie od tego masz pole "lapsRaceCount". To jedyne, potrzebne nam pole, z tych trzech, które obecnie znajdują się w configu. Pozostałe dwa proponuję usunąć.

**Comment by jaroslawfrydrych** [comment]
Zgoda
