### ISSUE TITLE
Layout z wynikami

### ISSUE THREAD

**Issue by Nickesh** [MX-5ClubPoland/MMCLapTimer#6]
Trzeba dokończyć layout ekranu dla sesji treningowych (practice) i utworzyć drugi layout - dla sesji mierzonej (rallysprint).

W obu przypadkach trzeba podzielić wyniki na klasy wyścigowe i ułożyć je na ekranie wg następujących założeń:
a) są trzy klasy wyścigowe,
b) jedna z klas wyścigowych ma podobną liczebność, jak pozostałe dwie razem.

**Comment by zrwsk** [comment]
Zwróć uwagę na mobilki ;)

![33072ffd-9a81-454d-9b00-7ff27d5249d8](https://cloud.githubusercontent.com/assets/9089600/15123090/4944106a-1622-11e6-97b6-874bb942c255.png)

**Comment by Nickesh** [comment]
Jak widzisz, zwróciłem :D
Jedyną logiczną opcją wydawało mi się zasłonięcie nicka przez czas. Jak nie ma miejsca na nick, to przynajmniej czas powinien być widoczny, bo poza nickiem zawsze jeszcze zostaje numer kierowcy. 

Jak masz jakiś lepszy pomysł, to zrobimy to w kolejnej iteracji. Na ten moment już nie bardzo jest czas, a poza tym, na screenshocie masz tylko fragment pełnego layoutu. Na docelowej wersji będzie o wiele więcej pasków, więc będą niższe, więc czas nie będzie nachodził na nicka ;)

**Comment by zrwsk** [comment]
IMO, wyrzuciłeś bardzo ważną informację ;)

Raczej szedłbym w kierunku wyrzucania (w kolejności od najmniej potrzebnego):
- numeru porządkowego
- numeru zawodnika
- czasu ostatniego przejazdu (wizualnie może zostać, ale sam czas - czy jest potrzebny skoro wiemy że jest gorzej?)

**Comment by Nickesh** [comment]
Zdecydowałem się wyrzucić nick nie dlatego, że jest mało istotny, ale dlatego, że jest największym elementem. Z wyrzucenia numeru startowego nie byłoby dużej korzyści (mało uzyskanego miejsca). 

Jeśli chodzi o numer pozycji to chyba też jest kluczowy, szczególnie przy dłuższej liście i dla zawodników z dalszych miejsc. No i znowu: jej wyrzucenie nie daje dużej korzyści. Ale w sumie można by iść w tym kierunku.

Ostatni czas zawodnika to wymaganie, że tak powiem odgórne - Dżunior mówił, że to dla nich istotne, żeby właśnie ten ostatni czas był na wykresach. Skonsultujemy się z nim na afterku po II rundzie ;)

Tak, czy inaczej, na screenshocie powyżej masz sytuację, która na serio nigdy nie powinna się zdarzyć. Po pierwsze viewport ma zawężoną szerokość do 70%, a po drugie, na tej liście powinno się znaleźć co najmniej 31 zawodników.

Ten ficzer miał bardziej na celu częściowe zasłonięcie końcówki bardzo długich nicków, jeśli takie się przydarzą, a nie całkowite ich zakrycie. Zobaczymy jak to wygląda na pełnym layoucie sesji. A ukrywanie pozycji i numeru startowego widzę tylko w takiej opcji, że przy określonej szerokości paska, zwijają się całkowicie od razu, a nie stopniowo, jak teraz nick. Tylko, że do tej pory layout skaluje się wyłącznie dzięki czystym CSS-om, a taka zmiana wymagałaby użycia do tego JavaScriptu.

**Comment by zrwsk** [comment]
Przez to, że w poprzednio wybranym arkuszu było tak mało zawodników, to jakoś sobie ułożyłem w głowie, że wyświetla się kilkanaście najlepszych.

Trzeba by przemyśleć ten layout - jak duży telewizor jest na rundach?

Teraz wysokość barów przeliczana jest wyłącznie ze względu na wysokość viewportu. Bardzo fajnie to wygląda, ale zastanawiam się nad użytecznością - chyba idealnie byłoby gdyby wyniki na telewizorze były widoczne z daleka. W tym momencie większość ekranu zajmują puste paski, które nic tak naprawdę sobą nie wnoszą. Może podzielić to na dwie kolumny, wtedy czcionka byłaby 2x większa? 

A na telefonie przy długiej liście można by pomyśleć o scrollu.

Dobrze, już więcej nie narzekam, przy większej ilości zawodników możemy uznać że jest ok. A pomysły na impovements'y lepiej pozbierać z pola walki ;)

**Comment by Nickesh** [comment]
Przeczytaj jeszcze raz pierwszy komentarz w tym issue. Są dwa założenia, z których wynika, że najliczniejsza klasa będzie po jednej stronie ekranu, zajmując połowę jego szerokości. Dwie pozostałe klasy będą po drugiej stronie ekranu, jedna po drugą, również razem zajmując połowę wysokości.

**Comment by zrwsk** [comment]
Ok, już wszystko wiem ;)

**Comment by Nickesh** [comment]
Zrobione.
